.catalog:
  name: "MYSQL"
  version: "v1"
  description: "My MYSQL Application Catalog"
  questions: 
    - variable: "MYSQL_MASTER_PASSWORD"
      label: "Mysql master password"
      description: "Password for the mysql root user"
      required: true
      type: "password"
      default: password
    - variable: "DATABASE_NAME"
      label: "Mysql database name"
      description: "Database name"
      required: true
      type: "string"
    - variable: "USER_NAME"
      label: "Mysql user"
      description: "User name for the MySql database"
      required: true
      type: "string"
    - variable: "MYSQL_PASSWORD"
      label: "Mysql password for the user "
      description: "Password for the mysql user"
      required: true
      type: "password"
      default: password
    - variable: "HOST_MYSQL_PORT"
      label: "Port to be exposed on the host"
      description: "Port that is going to be exposed in the host"
      required: true
      type: "string"
